#!/bin/bash
#==================================================================================================
#
#  Run script for the dvecdvecadd module of the Blaze test suite
#
#  Copyright (C) 2013 Klaus Iglberger - All Rights Reserved
#
#  This file is part of the Blaze library. You can redistribute it and/or modify it under
#  the terms of the New (Revised) BSD License. Redistribution and use in source and binary
#  forms, with or without modification, are permitted provided that the following conditions
#  are met:
#
#  1. Redistributions of source code must retain the above copyright notice, this list of
#     conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright notice, this list
#     of conditions and the following disclaimer in the documentation and/or other materials
#     provided with the distribution.
#  3. Neither the names of the Blaze development group nor the names of its contributors
#     may be used to endorse or promote products derived from this software without specific
#     prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
#  EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
#  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT
#  SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
#  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
#  TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
#  BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
#  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
#  DAMAGE.
#
#==================================================================================================


PATH_DVECDVECADD=$( dirname "${BASH_SOURCE[0]}" )

echo " Running dense vector/dense vector addition tests..."

$PATH_DVECDVECADD/V2aV2a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/V2aV2b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/V2aVDa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/V2aVDb; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/V2bV2a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/V2bV2b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/V2bVDa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/V2bVDb; if [ $? != 0 ]; then exit 1; fi

$PATH_DVECDVECADD/V3aV3a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/V3aV3b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/V3aVDa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/V3aVDb; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/V3bV3a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/V3bV3b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/V3bVDa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/V3bVDb; if [ $? != 0 ]; then exit 1; fi

$PATH_DVECDVECADD/V4aV4a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/V4aV4b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/V4aVDa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/V4aVDb; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/V4bV4a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/V4bV4b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/V4bVDa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/V4bVDb; if [ $? != 0 ]; then exit 1; fi

$PATH_DVECDVECADD/V5aV5a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/V5aV5b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/V5aVDa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/V5aVDb; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/V5bV5a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/V5bV5b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/V5bVDa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/V5bVDb; if [ $? != 0 ]; then exit 1; fi

$PATH_DVECDVECADD/V6aV6a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/V6aV6b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/V6aVDa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/V6aVDb; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/V6aVHa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/V6aVHb; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/V6bV6a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/V6bV6b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/V6bVDa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/V6bVDb; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/V6bVHa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/V6bVHb; if [ $? != 0 ]; then exit 1; fi

$PATH_DVECDVECADD/VDaV2a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/VDaV2b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/VDaV3a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/VDaV3b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/VDaV4a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/VDaV4b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/VDaV5a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/VDaV5b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/VDaV6a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/VDaV6b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/VDaVDa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/VDaVDb; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/VDaVHa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/VDaVHb; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/VDbV2a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/VDbV2b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/VDbV3a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/VDbV3b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/VDbV4a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/VDbV4b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/VDbV5a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/VDbV5b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/VDbV6a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/VDbV6b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/VDbVDa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/VDbVDb; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/VDbVHa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/VDbVHb; if [ $? != 0 ]; then exit 1; fi

$PATH_DVECDVECADD/VHaV6a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/VHaV6b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/VHaVDa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/VHaVDb; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/VHaVHa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/VHaVHb; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/VHbV6a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/VHbV6b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/VHbVDa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/VHbVDb; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/VHbVHa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECADD/VHbVHb; if [ $? != 0 ]; then exit 1; fi

$PATH_DVECDVECADD/AliasingTest; if [ $? != 0 ]; then exit 1; fi
