#!/bin/bash
#==================================================================================================
#
#  Run script for the intrinsics module of the Blaze test suite
#
#  Copyright (C) 2011 Klaus Iglberger - All Rights Reserved
#
#  This file is part of the Blaze library. This library is free software; you can redistribute
#  it and/or modify it under the terms of the GNU General Public License as published by the
#  Free Software Foundation; either version 3, or (at your option) any later version.
#
#  This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
#  without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#  See the GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License along with a special
#  exception for linking and compiling against the Blaze library, the so-called "runtime
#  exception"; see the file COPYING. If not, see http://www.gnu.org/licenses/.
#
#==================================================================================================


PATH_INTRINSICS=$( dirname "${BASH_SOURCE[0]}" )

echo " Running intrinsics tests..."

$PATH_INTRINSICS/Short;         if [ $? != 0 ]; then exit 1; fi
$PATH_INTRINSICS/UnsignedShort; if [ $? != 0 ]; then exit 1; fi
$PATH_INTRINSICS/Int;           if [ $? != 0 ]; then exit 1; fi
$PATH_INTRINSICS/UnsignedInt;   if [ $? != 0 ]; then exit 1; fi
$PATH_INTRINSICS/Long;          if [ $? != 0 ]; then exit 1; fi
$PATH_INTRINSICS/UnsignedLong;  if [ $? != 0 ]; then exit 1; fi
$PATH_INTRINSICS/Float;         if [ $? != 0 ]; then exit 1; fi
$PATH_INTRINSICS/Double;        if [ $? != 0 ]; then exit 1; fi
$PATH_INTRINSICS/ComplexFloat;  if [ $? != 0 ]; then exit 1; fi
$PATH_INTRINSICS/ComplexDouble; if [ $? != 0 ]; then exit 1; fi
