#!/bin/bash
#==================================================================================================
#
#  Run script for the Blaze test suite
#
#  Copyright (C) 2012-2020 Klaus Iglberger - All Rights Reserved
#
#  This file is part of the Blaze library. You can redistribute it and/or modify it under
#  the terms of the New (Revised) BSD License. Redistribution and use in source and binary
#  forms, with or without modification, are permitted provided that the following conditions
#  are met:
#
#  1. Redistributions of source code must retain the above copyright notice, this list of
#     conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright notice, this list
#     of conditions and the following disclaimer in the documentation and/or other materials
#     provided with the distribution.
#  3. Neither the names of the Blaze development group nor the names of its contributors
#     may be used to endorse or promote products derived from this software without specific
#     prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
#  EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
#  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT
#  SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
#  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
#  TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
#  BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
#  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
#  DAMAGE.
#
#==================================================================================================


BLAZETEST_PATH=$( dirname "${BASH_SOURCE[0]}" )


#==================================================================================================
# Mathematical Shims
#==================================================================================================

$BLAZETEST_PATH/src/mathtest/shims/run; if [ $? != 0 ]; then exit 1; fi


#==================================================================================================
# SIMD Operations
#==================================================================================================

$BLAZETEST_PATH/src/mathtest/simd/run; if [ $? != 0 ]; then exit 1; fi


#==================================================================================================
# BLAS Operations
#==================================================================================================

$BLAZETEST_PATH/src/mathtest/blas/run; if [ $? != 0 ]; then exit 1; fi


#==================================================================================================
# LAPACK Operations
#==================================================================================================

$BLAZETEST_PATH/src/mathtest/lapack/run; if [ $? != 0 ]; then exit 1; fi


#==================================================================================================
# Traits
#==================================================================================================

$BLAZETEST_PATH/src/mathtest/traits/run; if [ $? != 0 ]; then exit 1; fi


#==================================================================================================
# Type Traits
#==================================================================================================

$BLAZETEST_PATH/src/mathtest/typetraits/run; if [ $? != 0 ]; then exit 1; fi


#==================================================================================================
# Vectors
#==================================================================================================

$BLAZETEST_PATH/src/mathtest/vectors/run; if [ $? != 0 ]; then exit 1; fi


#==================================================================================================
# DenseMatrix
#==================================================================================================

$BLAZETEST_PATH/src/mathtest/densematrix/run; if [ $? != 0 ]; then exit 1; fi


#==================================================================================================
# StaticMatrix
#==================================================================================================

$BLAZETEST_PATH/src/mathtest/staticmatrix/run; if [ $? != 0 ]; then exit 1; fi


#==================================================================================================
# HybridMatrix
#==================================================================================================

$BLAZETEST_PATH/src/mathtest/hybridmatrix/run; if [ $? != 0 ]; then exit 1; fi


#==================================================================================================
# DynamicMatrix
#==================================================================================================

$BLAZETEST_PATH/src/mathtest/dynamicmatrix/run; if [ $? != 0 ]; then exit 1; fi


#==================================================================================================
# CustomMatrix
#==================================================================================================

$BLAZETEST_PATH/src/mathtest/custommatrix/run; if [ $? != 0 ]; then exit 1; fi


#==================================================================================================
# SparseMatrix
#==================================================================================================

$BLAZETEST_PATH/src/mathtest/sparsematrix/run; if [ $? != 0 ]; then exit 1; fi


#==================================================================================================
# CompressedMatrix
#==================================================================================================

$BLAZETEST_PATH/src/mathtest/compressedmatrix/run; if [ $? != 0 ]; then exit 1; fi


#==================================================================================================
# Adaptors
#==================================================================================================

$BLAZETEST_PATH/src/mathtest/adaptors/run; if [ $? != 0 ]; then exit 1; fi


#==================================================================================================
# Views
#==================================================================================================

$BLAZETEST_PATH/src/mathtest/views/run; if [ $? != 0 ]; then exit 1; fi


#==================================================================================================
# Operations
#==================================================================================================

$BLAZETEST_PATH/src/mathtest/operations/run; if [ $? != 0 ]; then exit 1; fi


#==================================================================================================
# MatrixSerializer
#==================================================================================================

$BLAZETEST_PATH/src/mathtest/matrixserializer/run; if [ $? != 0 ]; then exit 1; fi


#==================================================================================================
# AlignedAllocator
#==================================================================================================

$BLAZETEST_PATH/src/utiltest/alignedallocator/run; if [ $? != 0 ]; then exit 1; fi


#==================================================================================================
# Memory
#==================================================================================================

$BLAZETEST_PATH/src/utiltest/memory/run; if [ $? != 0 ]; then exit 1; fi


#==================================================================================================
# Numeric cast
#==================================================================================================

$BLAZETEST_PATH/src/utiltest/numericcast/run; if [ $? != 0 ]; then exit 1; fi


#==================================================================================================
# Type Traits
#==================================================================================================

$BLAZETEST_PATH/src/utiltest/typetraits/run; if [ $? != 0 ]; then exit 1; fi


#==================================================================================================
# Value Traits
#==================================================================================================

$BLAZETEST_PATH/src/utiltest/valuetraits/run; if [ $? != 0 ]; then exit 1; fi
