#!/bin/bash
#==================================================================================================
#
#  Run script for the dvecdvecmult module of the Blaze test suite
#
#  Copyright (C) 2013 Klaus Iglberger - All Rights Reserved
#
#  This file is part of the Blaze library. You can redistribute it and/or modify it under
#  the terms of the New (Revised) BSD License. Redistribution and use in source and binary
#  forms, with or without modification, are permitted provided that the following conditions
#  are met:
#
#  1. Redistributions of source code must retain the above copyright notice, this list of
#     conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright notice, this list
#     of conditions and the following disclaimer in the documentation and/or other materials
#     provided with the distribution.
#  3. Neither the names of the Blaze development group nor the names of its contributors
#     may be used to endorse or promote products derived from this software without specific
#     prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
#  EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
#  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT
#  SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
#  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
#  TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
#  BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
#  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
#  DAMAGE.
#
#==================================================================================================


PATH_DVECDVECMULT=$( dirname "${BASH_SOURCE[0]}" )

echo " Running dense vector/dense vector multiplication tests...";

$PATH_DVECDVECMULT/V2aV2a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V2aV2b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V2aVDa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V2aVDb; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V2bV2a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V2bV2b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V2bVDa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V2bVDb; if [ $? != 0 ]; then exit 1; fi

$PATH_DVECDVECMULT/V3aV3a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V3aV3b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V3aVDa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V3aVDb; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V3bV3a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V3bV3b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V3bVDa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V3bVDb; if [ $? != 0 ]; then exit 1; fi

$PATH_DVECDVECMULT/V4aV4a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V4aV4b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V4aVDa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V4aVDb; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V4bV4a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V4bV4b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V4bVDa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V4bVDb; if [ $? != 0 ]; then exit 1; fi

$PATH_DVECDVECMULT/V5aV5a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V5aV5b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V5aVDa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V5aVDb; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V5bV5a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V5bV5b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V5bVDa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V5bVDb; if [ $? != 0 ]; then exit 1; fi

$PATH_DVECDVECMULT/V6aV6a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V6aV6b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V6aVDa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V6aVDb; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V6bV6a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V6bV6b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V6bVDa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V6bVDb; if [ $? != 0 ]; then exit 1; fi

$PATH_DVECDVECMULT/VDaV2a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/VDaV2b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/VDaV3a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/VDaV3b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/VDaV4a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/VDaV4b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/VDaV5a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/VDaV5b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/VDaV6a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/VDaV6b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/VDaVDa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/VDaVDb; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/VDbV2a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/VDbV2b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/VDbV3a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/VDbV3b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/VDbV4a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/VDbV4b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/VDbV5a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/VDbV5b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/VDbV6a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/VDbV6b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/VDbVDa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/VDbVDb; if [ $? != 0 ]; then exit 1; fi

$PATH_DVECDVECMULT/AliasingTest; if [ $? != 0 ]; then exit 1; fi
