#!/bin/bash
#==================================================================================================
#
#  Run script for the dvecdvecmult module of the Blaze test suite
#
#  Copyright (C) 2011 Klaus Iglberger - All Rights Reserved
#
#  This file is part of the Blaze library. This library is free software; you can redistribute
#  it and/or modify it under the terms of the GNU General Public License as published by the
#  Free Software Foundation; either version 3, or (at your option) any later version.
#
#  This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
#  without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#  See the GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License along with a special
#  exception for linking and compiling against the Blaze library, the so-called "runtime
#  exception"; see the file COPYING. If not, see http://www.gnu.org/licenses/.
#
#==================================================================================================


PATH_DVECDVECMULT=$( dirname "${BASH_SOURCE[0]}" )

echo " Running dense vector/dense vector multiplication tests...";

$PATH_DVECDVECMULT/V2aV2a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V2aV2b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V2aVDa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V2aVDb; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V2bV2a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V2bV2b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V2bVDa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V2bVDb; if [ $? != 0 ]; then exit 1; fi

$PATH_DVECDVECMULT/V3aV3a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V3aV3b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V3aVDa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V3aVDb; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V3bV3a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V3bV3b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V3bVDa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V3bVDb; if [ $? != 0 ]; then exit 1; fi

$PATH_DVECDVECMULT/V4aV4a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V4aV4b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V4aVDa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V4aVDb; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V4bV4a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V4bV4b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V4bVDa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V4bVDb; if [ $? != 0 ]; then exit 1; fi

$PATH_DVECDVECMULT/V5aV5a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V5aV5b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V5aVDa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V5aVDb; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V5bV5a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V5bV5b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V5bVDa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V5bVDb; if [ $? != 0 ]; then exit 1; fi

$PATH_DVECDVECMULT/V6aV6a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V6aV6b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V6aVDa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V6aVDb; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V6bV6a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V6bV6b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V6bVDa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/V6bVDb; if [ $? != 0 ]; then exit 1; fi

$PATH_DVECDVECMULT/VDaV2a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/VDaV2b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/VDaV3a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/VDaV3b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/VDaV4a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/VDaV4b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/VDaV5a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/VDaV5b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/VDaV6a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/VDaV6b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/VDaVDa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/VDaVDb; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/VDbV2a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/VDbV2b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/VDbV3a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/VDbV3b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/VDbV4a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/VDbV4b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/VDbV5a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/VDbV5b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/VDbV6a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/VDbV6b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/VDbVDa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECMULT/VDbVDb; if [ $? != 0 ]; then exit 1; fi

$PATH_DVECDVECMULT/AliasingTest; if [ $? != 0 ]; then exit 1; fi
