#!/bin/bash
#==================================================================================================
#
#  Run script for the tsvecdmatmult module of the Blaze test suite
#
#  Copyright (C) 2011 Klaus Iglberger - All Rights Reserved
#
#  This file is part of the Blaze library. This library is free software; you can redistribute
#  it and/or modify it under the terms of the GNU General Public License as published by the
#  Free Software Foundation; either version 3, or (at your option) any later version.
#
#  This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
#  without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#  See the GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License along with a special
#  exception for linking and compiling against the Blaze library, the so-called "runtime
#  exception"; see the file COPYING. If not, see http://www.gnu.org/licenses/.
#
#==================================================================================================


PATH_TSVECDMATMULT=$( dirname "${BASH_SOURCE[0]}" )

echo " Running sparse vector/dense matrix multiplication tests...";

$PATH_TSVECDMATMULT/VCaM2x2a;  if [ $? != 0 ]; then exit 1; fi
$PATH_TSVECDMATMULT/VCaM2x2b;  if [ $? != 0 ]; then exit 1; fi
$PATH_TSVECDMATMULT/VCaM3x3a;  if [ $? != 0 ]; then exit 1; fi
$PATH_TSVECDMATMULT/VCaM3x3b;  if [ $? != 0 ]; then exit 1; fi
$PATH_TSVECDMATMULT/VCaM4x4a;  if [ $? != 0 ]; then exit 1; fi
$PATH_TSVECDMATMULT/VCaM4x4b;  if [ $? != 0 ]; then exit 1; fi
$PATH_TSVECDMATMULT/VCaM5x5a;  if [ $? != 0 ]; then exit 1; fi
$PATH_TSVECDMATMULT/VCaM5x5b;  if [ $? != 0 ]; then exit 1; fi
$PATH_TSVECDMATMULT/VCaM6x6a;  if [ $? != 0 ]; then exit 1; fi
$PATH_TSVECDMATMULT/VCaM6x6b;  if [ $? != 0 ]; then exit 1; fi
$PATH_TSVECDMATMULT/VCaM7x13a; if [ $? != 0 ]; then exit 1; fi
$PATH_TSVECDMATMULT/VCaM7x13b; if [ $? != 0 ]; then exit 1; fi
$PATH_TSVECDMATMULT/VCaM16x8a; if [ $? != 0 ]; then exit 1; fi
$PATH_TSVECDMATMULT/VCaM16x8b; if [ $? != 0 ]; then exit 1; fi
$PATH_TSVECDMATMULT/VCaMDa;    if [ $? != 0 ]; then exit 1; fi
$PATH_TSVECDMATMULT/VCaMDb;    if [ $? != 0 ]; then exit 1; fi

$PATH_TSVECDMATMULT/VCbM2x2a;  if [ $? != 0 ]; then exit 1; fi
$PATH_TSVECDMATMULT/VCbM2x2b;  if [ $? != 0 ]; then exit 1; fi
$PATH_TSVECDMATMULT/VCbM3x3a;  if [ $? != 0 ]; then exit 1; fi
$PATH_TSVECDMATMULT/VCbM3x3b;  if [ $? != 0 ]; then exit 1; fi
$PATH_TSVECDMATMULT/VCbM4x4a;  if [ $? != 0 ]; then exit 1; fi
$PATH_TSVECDMATMULT/VCbM4x4b;  if [ $? != 0 ]; then exit 1; fi
$PATH_TSVECDMATMULT/VCbM5x5a;  if [ $? != 0 ]; then exit 1; fi
$PATH_TSVECDMATMULT/VCbM5x5b;  if [ $? != 0 ]; then exit 1; fi
$PATH_TSVECDMATMULT/VCbM6x6a;  if [ $? != 0 ]; then exit 1; fi
$PATH_TSVECDMATMULT/VCbM6x6b;  if [ $? != 0 ]; then exit 1; fi
$PATH_TSVECDMATMULT/VCbM7x13a; if [ $? != 0 ]; then exit 1; fi
$PATH_TSVECDMATMULT/VCbM7x13b; if [ $? != 0 ]; then exit 1; fi
$PATH_TSVECDMATMULT/VCbM16x8a; if [ $? != 0 ]; then exit 1; fi
$PATH_TSVECDMATMULT/VCbM16x8b; if [ $? != 0 ]; then exit 1; fi
$PATH_TSVECDMATMULT/VCbMDa;    if [ $? != 0 ]; then exit 1; fi
$PATH_TSVECDMATMULT/VCbMDb;    if [ $? != 0 ]; then exit 1; fi

$PATH_TSVECDMATMULT/AliasingTest; if [ $? != 0 ]; then exit 1; fi
