#!/bin/bash
#==================================================================================================
#
#  Run script for the dvecdveccross module of the Blaze test suite
#
#  Copyright (C) 2011 Klaus Iglberger - All Rights Reserved
#
#  This file is part of the Blaze library. This library is free software; you can redistribute
#  it and/or modify it under the terms of the GNU General Public License as published by the
#  Free Software Foundation; either version 3, or (at your option) any later version.
#
#  This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
#  without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#  See the GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License along with a special
#  exception for linking and compiling against the Blaze library, the so-called "runtime
#  exception"; see the file COPYING. If not, see http://www.gnu.org/licenses/.
#
#==================================================================================================


PATH_DVECDVECCROSS=$( dirname "${BASH_SOURCE[0]}" )

echo " Running dense vector/dense vector cross product tests...";

$PATH_DVECDVECCROSS/V3aV3a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECCROSS/V3aV3b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECCROSS/V3aVDa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECCROSS/V3aVDb; if [ $? != 0 ]; then exit 1; fi

$PATH_DVECDVECCROSS/V3bV3a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECCROSS/V3bV3b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECCROSS/V3bVDa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECCROSS/V3bVDb; if [ $? != 0 ]; then exit 1; fi

$PATH_DVECDVECCROSS/VDaV3a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECCROSS/VDaV3b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECCROSS/VDaVDa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECCROSS/VDaVDb; if [ $? != 0 ]; then exit 1; fi

$PATH_DVECDVECCROSS/VDbV3a; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECCROSS/VDbV3b; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECCROSS/VDbVDa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECDVECCROSS/VDbVDb; if [ $? != 0 ]; then exit 1; fi

$PATH_DVECDVECCROSS/AliasingTest; if [ $? != 0 ]; then exit 1; fi
