#!/bin/bash
#==================================================================================================
#
#  Run script for the svecdveccross module of the Blaze test suite
#
#  Copyright (C) 2011 Klaus Iglberger - All Rights Reserved
#
#  This file is part of the Blaze library. This library is free software; you can redistribute
#  it and/or modify it under the terms of the GNU General Public License as published by the
#  Free Software Foundation; either version 3, or (at your option) any later version.
#
#  This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
#  without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#  See the GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License along with a special
#  exception for linking and compiling against the Blaze library, the so-called "runtime
#  exception"; see the file COPYING. If not, see http://www.gnu.org/licenses/.
#
#==================================================================================================


PATH_SVECDVECCROSS=$( dirname "${BASH_SOURCE[0]}" )

echo " Running sparse vector/dense vector cross product tests...";

$PATH_SVECDVECCROSS/VCaV3a; if [ $? != 0 ]; then exit 1; fi
$PATH_SVECDVECCROSS/VCaV3b; if [ $? != 0 ]; then exit 1; fi
$PATH_SVECDVECCROSS/VCaVDa; if [ $? != 0 ]; then exit 1; fi
$PATH_SVECDVECCROSS/VCaVDb; if [ $? != 0 ]; then exit 1; fi

$PATH_SVECDVECCROSS/VCbV3a; if [ $? != 0 ]; then exit 1; fi
$PATH_SVECDVECCROSS/VCbV3b; if [ $? != 0 ]; then exit 1; fi
$PATH_SVECDVECCROSS/VCbVDa; if [ $? != 0 ]; then exit 1; fi
$PATH_SVECDVECCROSS/VCbVDb; if [ $? != 0 ]; then exit 1; fi

$PATH_SVECDVECCROSS/AliasingTest; if [ $? != 0 ]; then exit 1; fi
