#!/bin/bash
#==================================================================================================
#
#  Run script for the dvecsvecsub module of the Blaze test suite
#
#  Copyright (C) 2011 Klaus Iglberger - All Rights Reserved
#
#  This file is part of the Blaze library. This library is free software; you can redistribute
#  it and/or modify it under the terms of the GNU General Public License as published by the
#  Free Software Foundation; either version 3, or (at your option) any later version.
#
#  This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
#  without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#  See the GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License along with a special
#  exception for linking and compiling against the Blaze library, the so-called "runtime
#  exception"; see the file COPYING. If not, see http://www.gnu.org/licenses/.
#
#==================================================================================================


PATH_DVECSVECSUB=$( dirname "${BASH_SOURCE[0]}" )

echo " Running dense vector/sparse vector subtraction tests...";

$PATH_DVECSVECSUB/V2aVCa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECSVECSUB/V2aVCb; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECSVECSUB/V2bVCa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECSVECSUB/V2bVCb; if [ $? != 0 ]; then exit 1; fi

$PATH_DVECSVECSUB/V3aVCa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECSVECSUB/V3aVCb; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECSVECSUB/V3bVCa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECSVECSUB/V3bVCb; if [ $? != 0 ]; then exit 1; fi

$PATH_DVECSVECSUB/V4aVCa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECSVECSUB/V4aVCb; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECSVECSUB/V4bVCa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECSVECSUB/V4bVCb; if [ $? != 0 ]; then exit 1; fi

$PATH_DVECSVECSUB/V5aVCa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECSVECSUB/V5aVCb; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECSVECSUB/V5bVCa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECSVECSUB/V5bVCb; if [ $? != 0 ]; then exit 1; fi

$PATH_DVECSVECSUB/V6aVCa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECSVECSUB/V6aVCb; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECSVECSUB/V6bVCa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECSVECSUB/V6bVCb; if [ $? != 0 ]; then exit 1; fi

$PATH_DVECSVECSUB/VDaVCa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECSVECSUB/VDaVCb; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECSVECSUB/VDbVCa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECSVECSUB/VDbVCb; if [ $? != 0 ]; then exit 1; fi

$PATH_DVECSVECSUB/AliasingTest; if [ $? != 0 ]; then exit 1; fi
