#!/bin/bash
#==================================================================================================
#
#  Run script for the dvectsvecmult module of the Blaze test suite
#
#  Copyright (C) 2013 Klaus Iglberger - All Rights Reserved
#
#  This file is part of the Blaze library. You can redistribute it and/or modify it under
#  the terms of the New (Revised) BSD License. Redistribution and use in source and binary
#  forms, with or without modification, are permitted provided that the following conditions
#  are met:
#
#  1. Redistributions of source code must retain the above copyright notice, this list of
#     conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright notice, this list
#     of conditions and the following disclaimer in the documentation and/or other materials
#     provided with the distribution.
#  3. Neither the names of the Blaze development group nor the names of its contributors
#     may be used to endorse or promote products derived from this software without specific
#     prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
#  EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
#  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT
#  SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
#  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
#  TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
#  BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
#  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
#  DAMAGE.
#
#==================================================================================================


PATH_DVECTSVECMULT=$( dirname "${BASH_SOURCE[0]}" )

echo " Running dense vector/sparse vector outer product tests...";

$PATH_DVECTSVECMULT/V2aVCa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECTSVECMULT/V2aVCb; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECTSVECMULT/V2bVCa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECTSVECMULT/V2bVCb; if [ $? != 0 ]; then exit 1; fi

$PATH_DVECTSVECMULT/V3aVCa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECTSVECMULT/V3aVCb; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECTSVECMULT/V3bVCa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECTSVECMULT/V3bVCb; if [ $? != 0 ]; then exit 1; fi

$PATH_DVECTSVECMULT/V4aVCa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECTSVECMULT/V4aVCb; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECTSVECMULT/V4bVCa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECTSVECMULT/V4bVCb; if [ $? != 0 ]; then exit 1; fi

$PATH_DVECTSVECMULT/V5aVCa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECTSVECMULT/V5aVCb; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECTSVECMULT/V5bVCa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECTSVECMULT/V5bVCb; if [ $? != 0 ]; then exit 1; fi

$PATH_DVECTSVECMULT/V6aVCa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECTSVECMULT/V6aVCb; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECTSVECMULT/V6bVCa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECTSVECMULT/V6bVCb; if [ $? != 0 ]; then exit 1; fi

$PATH_DVECTSVECMULT/VDaVCa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECTSVECMULT/VDaVCb; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECTSVECMULT/VDbVCa; if [ $? != 0 ]; then exit 1; fi
$PATH_DVECTSVECMULT/VDbVCb; if [ $? != 0 ]; then exit 1; fi

$PATH_DVECTSVECMULT/AliasingTest; if [ $? != 0 ]; then exit 1; fi
